"""create table users, comments, news

Revision ID: 35b888cf8c1a
Revises: 15ad5cab9992
Create Date: 2023-02-26 16:57:26.606251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "35b888cf8c1a"
down_revision = "15ad5cab9992"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("comments", sa.Column("news_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "comments", "news", ["news_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "comments", type_="foreignkey")
    op.drop_column("comments", "news_id")
    # ### end Alembic commands ###
