"""create table users, comments, news

Revision ID: 91a90da9652e
Revises: cae933f9e118
Create Date: 2023-02-26 16:14:45.879225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "91a90da9652e"
down_revision = "cae933f9e118"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
