"""create table users, comments, news

Revision ID: cae933f9e118
Revises: 
Create Date: 2023-02-26 16:09:22.340245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cae933f9e118"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
