"""create table users, comments, news

Revision ID: d146c53c17cd
Revises: f2bf8cfd78e2
Create Date: 2023-02-26 17:10:12.005396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d146c53c17cd"
down_revision = "f2bf8cfd78e2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("comments", sa.Column("new_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "comments", "news", ["new_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "comments", type_="foreignkey")
    op.drop_column("comments", "new_id")
    # ### end Alembic commands ###
