"""create table users, comments, news

Revision ID: da53e7d05ecb
Revises: dffc0ecf0876
Create Date: 2023-02-26 16:54:03.593975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "da53e7d05ecb"
down_revision = "dffc0ecf0876"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "comments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("new_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["new_id"],
            ["news.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("comments")
    # ### end Alembic commands ###
