"""create table users, comments, news

Revision ID: dffc0ecf0876
Revises: 8432fe6ba325
Create Date: 2023-02-26 16:47:38.749313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dffc0ecf0876"
down_revision = "8432fe6ba325"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "comments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("user_id_for_comment", sa.Integer(), nullable=True),
        sa.Column("new_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["new_id"],
            ["news.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id_for_comment"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("comments")
    # ### end Alembic commands ###
