"""create table users, comments, news

Revision ID: f2bf8cfd78e2
Revises: dc4b2a9ac8a7
Create Date: 2023-02-26 17:03:58.319456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f2bf8cfd78e2"
down_revision = "dc4b2a9ac8a7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("comments", sa.Column("news_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "comments", "news", ["news_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "comments", type_="foreignkey")
    op.drop_column("comments", "news_id")
    # ### end Alembic commands ###
