"""create table users, comments, news

Revision ID: f41eb3bc781e
Revises: d146c53c17cd
Create Date: 2023-02-26 17:12:43.663221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f41eb3bc781e"
down_revision = "d146c53c17cd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("comments", sa.Column("news_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "comments", "news", ["news_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "comments", type_="foreignkey")
    op.drop_column("comments", "news_id")
    # ### end Alembic commands ###
