"""create table users, comments, news

Revision ID: f90d01042aac
Revises: fcc675856de1
Create Date: 2023-02-26 17:15:06.974388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f90d01042aac"
down_revision = "fcc675856de1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
